### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by ziceptor** [trentech/ProjectPortals#73] opened 2017-09-03 22:49 UTC
projectcore-7.0.0-0.2.0.jar
projectportals-7.0.0-0.14.0.jar
spongeforge-1.12.1-2444-7.0.0-BETA-2609.jar
forge-1.12.1-14.22.0.2444-universal.jar

https://pastebin.com/Gj71QfZE

**Comment by trentech** [comment] 2017-11-09 23:12
duplicate of https://github.com/trentech/ProjectPortals/issues/68

**Closed by trentech** 2017-11-09 23:12 UTC
